### ISSUE TITLE
Dismissing  Issue

### ISSUE THREAD

**Issue by mohamedmontser** [lucaszischka/BottomSheet#109]
when opening a sheet on another sheet and clicking outside the two sheets it dismisses the two sheets.
And background sheet is clickable from the foreground one.

Expected behavior: 
Background View should not accessible from the sheet.

![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-23 at 07 10 05](https://user-images.githubusercontent.com/30370903/203473562-f4fa5a60-1c70-41d8-9587-12bdc7b09035.png)

**Additional context**
![Simulator Screen Shot - iPhone 14 Pro Max - 2022-11-23 at 07 10 05](https://user-images.githubusercontent.com/30370903/203473132-7c7223e9-e5b0-47d0-bcb8-9671e35bff13.png)

**Comment by lucaszischka** [comment]
Simply don’t use:

> `.enableTapToDismiss(Bool)`: Makes it possible to dismiss the BottomSheet by tapping somewhere else.
