### ISSUE TITLE
I does not open as a Bottom sheet on iPad

### ISSUE THREAD

**Issue by pausanchezv** [lucaszischka/BottomSheet#110]
When using iPad, a sort of modal view slides down from the top making the user experience awful. Whereas it works acceptable in iPhone it's a disaster in iPad. Version 2 was way better. It would be nice if you kept that version up to date instead of 3. Or improve version 3 so that is works as well as version 2 did. This is the only library I use that I'm not able to update and still have the app working well. Is there any trick so that it opens a bottom sheet when in iPad too?

Thanks.

**Comment by lucaszischka** [comment]
Have a look at the documentation:

> `.enableFloatingIPadSheet(Bool)`: Makes it possible to make the sheet appear like on iPhone.
