### ISSUE TITLE
Scrolling requires two time swipe

### ISSUE THREAD

**Issue by avnishyadav** [lucaszischka/BottomSheet#133]
First. Thanks for awesome library that makes life easier.

**Describe the bug**
If the bottom sheet is at top, user need to scroll twice to start working scrolling of main content.

**Expected behavior**
Content should scroll with one swipe only.

**Video**

https://github.com/lucaszischka/BottomSheet/assets/11243717/58b62857-f4b2-4278-9798-db137413cd50

**Comment by freeworld1995** [comment]
Hi, do you have sample code for this problem ?

**Comment by avnishyadav** [comment]
@freeworld1995 Sorry,  issue was from our side. Thanks!
