### ISSUE TITLE
Asset Build Input File cannot be found while Archiving

### ISSUE THREAD

**Issue by Awesomeplayer165** [lucaszischka/BottomSheet#134]
**Describe the bug**
While archiving my Xcode project, I encountered an error that says `Build Input File cannot be found: '.../DerivedData/Project/Build/Intermediates.noIndex'`. I believe this has to do with the Media assets holding xmark.circle images not being passed into the archiving process. My project compiles and runs without any errors, but fails when archiving. What am I doing wrong here? Thank you so much!

<img width="965" alt="image" src="https://github.com/lucaszischka/BottomSheet/assets/70717139/ebfee23b-1c59-4464-9119-1c5ba0f8993f">

<img width="901" alt="image" src="https://github.com/lucaszischka/BottomSheet/assets/70717139/85d433ed-768d-4766-aa10-80782cf61fcc">

<img width="280" alt="image" src="https://github.com/lucaszischka/BottomSheet/assets/70717139/b06f685d-86b6-487a-80b0-e6155068ff9b">

**Target version**
- Environment: iOS
- Version: Xcode Version 15.0 beta 3 (15A5195k)
- Package Manager: Swift PM

**Comment by Awesomeplayer165** [comment]
I have opened PR for this, @lucaszischka. Let me know when you are ready to go or if you want to suggest any changes. Thanks

**Comment by lucaszischka** [comment]
Hello,
as nobody else reported this issue jet I think this maybe related to your local configuration. Please also try cleaning your build folder, etc.. This could also just be beta related, as I myself (Beta 6) can't reproduce the issue.
