### ISSUE TITLE
View not redrawing when State/Binding data changes

### ISSUE THREAD

**Issue by Dave181295** [lucaszischka/BottomSheet#137]
```
  .bottomSheet(bottomSheetPosition: $bottomSheetPosition,
                     switchablePositions: [.dynamic, .hidden],
                     title: NSLocalizedString("Set up Social Login", comment: "")) {
            
//Updating binding In child view
            LinkAccountProviderView()
                .padding([.horizontal, .vertical])
                .padding([.bottom])
            
        }
```

Binding updates never trigger the view to redraw.

**Comment by lucaszischka** [comment]
Hello @Dave181295,
I don't understand your issue and can't reproduce it with the provided code. Please make sure that you handle view updates and state management/observation correctly. If you share more details on the issue, I will revisit and reopen it if applicable.
