### ISSUE TITLE
When TabView is present, tab items are displayed over the bottom sheet

### ISSUE THREAD

**Issue by uliashkevich** [lucaszischka/BottomSheet#146]
**Describe the bug**
When TabView is a parent of the view containing bottom sheet, tab items are displayed over the bottom sheet.

**Minimal reproduce-able code**
Use this preview code in BottomSheetTests project:
```
struct ContentView_Previews: PreviewProvider {
    static var previews: some View {
        @State var selectedTab = 0
        TabView(selection: $selectedTab) {
            ContentView()
                .tabItem {
                    Image(systemName: "person")
                    Text("Profile")
                }.tag(0)
        }
    }
}
```

**Expected behavior**
Bottom sheet should be always displayed on top of all the UI elements.

**Screenshots**
<img width="227" alt="Screenshot 2023-10-29 at 3 25 46 PM" src="https://github.com/lucaszischka/BottomSheet/assets/2330361/ddb89938-2e62-42cb-b195-a72af9f38f8b">

**Target version**
- Environment: iOS 15+
- Version: 3.1.1

**Comment by lucaszischka** [comment]
Hello @uliashkevich, @SpectralDragon, this is expected behaviour; if you want to display it above the TabView, you will have to move it up in the SwiftUI View Hierarchy see #60.
