### ISSUE TITLE
Bottomsheet doesn't lock orientation when app has only portrait mode.

### ISSUE THREAD

**Issue by SteeveFong** [lucaszischka/BottomSheet#165]
**Describe the bug**
The bottomsheet changes orientation when phone is on horizontal position even if the app support only portrait mode.

**Minimal reproduce-able code**
`
import MapKit
import SwiftUI
import BottomSheet

struct ContentView: View {
    @State var bottomSheetPosition: BottomSheetPosition = .relative(0.60) //1
        
    var body: some View {
    
        Map() //2
            .bottomSheet(
                bottomSheetPosition: $bottomSheetPosition,
                switchablePositions: [], 
                content: {
                    Text("test")
                }
            ) //3
    }
}
`

**Expected behavior**
The bottomsheet should lock orientation as well, it shouldn't be shrinking as shown in the clip below.

https://github.com/user-attachments/assets/c1bdeb9e-94ed-406f-b226-f4983877cd30

**Screenshots**

![Simulator Screenshot - iPhone 15 - 2024-07-30 at 11 10 27](https://github.com/user-attachments/assets/253bfeb1-182f-49f5-bb7d-6ad308c3aa70)

**Target version**
- Environment: iOS 17.2
- Version: Bottomsheet v3.1.1

**Additional context**

**Comment by mikejonas** [comment]
Try adding this property: `.sheetWidth(.relative(1))`

**Comment by SteeveFong** [comment]
it works, thanks
