### ISSUE TITLE
BottomSheetPosition not the same across device types

### ISSUE THREAD

**Issue by jordibruin** [lucaszischka/BottomSheet#26]
I've made a custom bottom sheet position, but it seems that the height percentage is not calculated in the same way for an iPhone XS Max and an iPhone 8 Plus.

I would expect that some space would be visible on top of the bottom sheet on the iPhone 8 Plus as well.

This is my custom bottomsheetPosition:
```
enum SettingsBottomSheetPosition: CGFloat, CaseIterable {
	case top = 0.95, middle = 0.8, hidden = 0
}
```

And these are my options:

```
let settingsOptions: [BottomSheet.Options] = [
		.swipeToDismiss, .tapToDissmiss, .showCloseButton(), .noBottomPosition, .background(AnyView(Color(.systemGroupedBackground))) ]
```

See screenshots:
![Simulator Screen Shot - iPhone 8 Plus - 2021-09-03 at 19 46 44](https://user-images.githubusercontent.com/170948/132048347-d6f6037e-fd2c-4a3a-bce2-238688746310.png)
![Simulator Screen Shot - iPhone 12 Max - 2021-09-03 at 19 41 57](https://user-images.githubusercontent.com/170948/132048366-1e1c1835-383d-41db-8055-6b9793d205a9.png)

**Comment by LucasMucGH** [comment]
Hello Jordi,

I‘m currently at vacation, but as soon as I’m back home I will have a look. My current guess is that is due to the `save area` differences between these devices.

Greetings,
Lucas

**Comment by jordibruin** [comment]
No rush Lucas, I will have a look myself as well! Thanks for making this great package 🙂
