### ISSUE TITLE
Drag indicator cannot be dragged to change sheet position

### ISSUE THREAD

**Issue by coughski** [lucaszischka/BottomSheet#45]
The grab indicator reacts to taps, but not to drag gestures. I have to drag on space adjacent on the indicator in order to change the sheet position via drag. Recorded this in the Xcode 13 preview canvas, iOS 15. Thanks for making the package!

``` swift
import SwiftUI
import BottomSheet

struct ContentView: View {
    @State var bottomSheetPosition: BottomSheetPosition = .bottom
    var body: some View {
        Text("Hello, world!")
            .bottomSheet(bottomSheetPosition: $bottomSheetPosition) {
                Text("Hi again")
            }
    }
}
```

https://user-images.githubusercontent.com/945761/149983243-f0289265-5ff6-4e5c-a3d8-2157ead6b1f2.mov

**Comment by lucaszischka** [comment]
Changed in upstream. Will be part of the next version.
