### ISSUE TITLE
Mode for absolute bottom positions except for top

### ISSUE THREAD

**Issue by aehlke** [lucaszischka/BottomSheet#48]
When using absolute bottom positions, it’s common to need the ‘top’ position to be at the top of the screen. It’s currently impossible to do this in a way that recomputes the ‘top’ when the window resizes or device rotates.

**Comment by lucaszischka** [comment]
I’m not sure if this is possible in a easy and understandable matter; what value would want to assign to the top case in your enum?

```swift
enum MyBottomSheetPosition: CGFloat, CaseIterable, Equatable {
    case top = //?
    case middle = 300
    case bottom = 100
    case hidden = 0
}
```

**Comment by lucaszischka** [comment]
I found a way how it could be implemented. This feature will come with the rewrite (v3).
