### ISSUE TITLE
Push new version to Cocoapods

### ISSUE THREAD

**Issue by svachmic** [lucaszischka/BottomSheet#50]
Hi @LucasMucGH , thanks a lot for a great lib!

I just noticed that the latest two versions did not make it to Cocoapods (attached screenshot). Perhaps you've forgotten to [push the tags to Cocoapods repo](https://stackoverflow.com/questions/41361399/how-to-publish-new-official-pod-version)?

![image](https://user-images.githubusercontent.com/1448888/151699338-c97f8935-b19a-4ddb-9e8f-981d4dde903b.png)

**Comment by anqus** [comment]
Also interested in 2.6.0 being pushed to CocoaPods.

**Comment by svachmic** [comment]
@LucasMucGH is there any way we could help you out here? Let me know, happy to give a hand.

**Comment by lucaszischka** [comment]
No I don't need help thank you, I just forgot to push it in the last 2 updates. I will push it to cocoapods as soon as I have time.

**Comment by harmittaa** [comment]
Also looking forward to the new version to be distributed with `CocoaPods`, I'm facing #31 fixed in #38. Thanks for the great work 👍

**Comment by lucaszischka** [comment]
Currently getting an internal server error, when trying to register (changed the email of the podspec). I will try to push the new version later/tomorrow again.

**Comment by lucaszischka** [comment]
Done
