### ISSUE TITLE
Content not responding to TapGestures

### ISSUE THREAD

**Issue by brenovaladao** [lucaszischka/BottomSheet#51]
I have a ScrollView with a list of items as the main content, and if I pass `.appleScrollBehavior` as an option, the tap gesture stops responding. It works when not passing it as an option

**Comment by CaryAndo** [comment]
I also get this problem in `2.6.0`, it seems `.appleScrollBehavior` has some quirks.

**Comment by LucasMucGH** [comment]
Yes, like mentioned in similar issues before, I will remove appleScrollBehavior soon, because it is really buggy and messes with ScrollViews, Lists and Gestures. No support for appleScrollBehavior will be provided anymore.

**Comment by lucaszischka** [comment]
This should be fixed in main. Please test these changes, before I release them. If your bug is still present or you find other bugs, please tell me.
