### ISSUE TITLE
How to change position state on swipe down 

### ISSUE THREAD

**Issue by mikeyyyzhao** [lucaszischka/BottomSheet#61]
First of all, great library!

I see that on swipe down, depending on how far you've swiped, the changes to a different state (.medium, .bottom, etc). However, is there a way to always go to a certain state on swipe down? For example, if I'm currently on .top and regardless of how far I swipe down, I always want to end up in the medium state. If I'm currently in the .medium state and regardless of how far I swipe down, I always end up in the .bottom state.

**Comment by lucaszischka** [comment]
No currently not. If I have time i can add this feature.

**Comment by lucaszischka** [comment]
I added an option to disable the flick through feature (`.disableFlickThrough`). Will be published later today.
