### ISSUE TITLE
Read translation value on drag

### ISSUE THREAD

**Issue by Dara-To** [lucaszischka/BottomSheet#62]
Looks like a great library! However, I need one exactly like this that would enable me to read translation value on drag gesture so I could use it to perform other animations, like the one below.

Check this one: https://github.com/Wouter125/BottomSheet

**Comment by Limoo** [comment]
I would also like to change the position/color of my content in relation to the relative drag position

**Comment by lucaszischka** [comment]
Looks complicated to add. If someone wants to speed up the addition of this feature, help in form of Pull Requests would be appreciated.

**Comment by lucaszischka** [comment]
Im currently rewriting the bottom sheet. The feature will soon be added.
