### ISSUE TITLE
Remove safe area

### ISSUE THREAD

**Issue by flowbe** [lucaszischka/BottomSheet#63]
I created a bottom sheet with scrollable content and a white background. The bottom sheet content has a safe area inset bottom that is not very beautiful. The only way I found to remove it is to add `.edgesIgnoringSafeArea(.bottom)` **after** the `.bottomSheet`, but this will also apply to my view. Is it possible to fix this in the library?

**First option:**
```swift
.bottomSheet(bottomSheetPosition: $bottomSheet.position, options: bottomSheetOptions) {
    switch bottomSheet.state {
    case let .actions(thread):
        ActionsView(target: .thread(thread))
    default:
        EmptyView()
    }
}
```
![Simulator Screen Shot - iPhone 13 - 2022-06-08 at 15 15 36](https://user-images.githubusercontent.com/8288625/172637158-98c07854-bc9b-49f2-83d6-7cb2cfe957ec.png)

**Second option:**
```swift
.bottomSheet(bottomSheetPosition: $bottomSheet.position, options: bottomSheetOptions) {
    switch bottomSheet.state {
    case let .actions(thread):
        ActionsView(target: .thread(thread))
    default:
        EmptyView()
    }
}
.edgesIgnoringSafeArea(.bottom)
```
![Simulator Screen Shot - iPhone 13 - 2022-06-08 at 15 15 17](https://user-images.githubusercontent.com/8288625/172637077-7093edf0-a792-4d64-89bb-812c6035ae26.png)

**Comment by lucaszischka** [comment]
I added an option to disable the save area insets (`.disableBottomSafeAreaInsets`). Will be published later today.

**Comment by flowbe** [comment]
Awesome, thank you!
