### ISSUE TITLE
Weird bottom sheet width when app's in split screen on landscape iPad

### ISSUE THREAD

**Issue by sdtaheri** [lucaszischka/BottomSheet#94]
**Describe the bug**
In **BottomSheetView+Calculations.swift**, in `width(with:)`, the logic doesn't look right. If the iPad is in landscape mode, and you put the app in split screen mode, the code goes into `UIDevice.current.orientation.isLandscape` block and sets the bottom sheet width to %40 of the app width.

**Minimal reproduce-able code**
I paste the problematic function:
```
    // For iPhone landscape, iPad and Mac support
    func width(with geometry: GeometryProxy) -> CGFloat {
#if os(macOS)
        // On Mac use 30% of the width
        return geometry.size.width * 0.3
#else
        if self.isIPadOrMac {
            // On iPad use 30% of the width
            return geometry.size.width * 0.3
        } else if UIDevice.current.orientation.isLandscape {
            // On iPhone landscape use of the 40% width
            return geometry.size.width * 0.4
        } else {
            // On iPhone portrait use of the 100% width
            return geometry.size.width
        }
#endif
    }
```

**Expected behavior**
I believe the sheet should follow the horizontal size class on iPad. The ideal would be to set a minimum width as an option. 

**Screenshots**
![Simulator Screen Shot - iPad Pro (11-inch) (3rd generation) - 2022-08-19 at 18 14 24](https://user-images.githubusercontent.com/57771530/185638113-c827b5a3-4d53-4f49-b0ec-260ce0abcffd.png)

**Target version**
- Environment: iPad, Catalyst, iOS app on the Mac and macOS
- Version: 15.6

**Comment by jeffphp** [comment]
If you want the BottomSheet to take all the available width, you can use 

BottomSheet{...}.sheetWidth(.relative(1))
