### ISSUE TITLE
Ignored keyboard safe area on iPhone.

### ISSUE THREAD

**Issue by VadimQw** [lucaszischka/BottomSheet#97]
**Describe the bug**
Keyboard safe area ignored if activated.

**Expected behavior**
Bottom sheet consider keyboard height.

**Target version**
- Environment: iOS
- Version: 15.0

**Additional context**
On 'BottomSheetView' use '.ignoresSafeArea(.container, edges: .bottom)' for iPhone instead '.edgesIgnoringSafeArea(.bottom)'.

**Comment by chocoford** [comment]
The problem is still here.

#### Target version

Environment: iOS
Version: 16.0

I have raised a PR #130, using `.ignoresSafeArea(.container, edges: .bottom)` to replace `'.edgesIgnoringSafeArea(.bottom)` for iOS version greater than `14.0`.
